spring.application.name=employee-management

# Active profile (change to prod on Render using an environment variable)
spring.profiles.active=local



# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries
spring.jpa.show-sql=true

# Format SQL
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000